spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PW}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}