spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PW}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}